name: Windows Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest

    env:
      PROJECT_NAME: ${{ github.event.repository.name }}
      PROJECT_BUILD_DIR: ${{ github.event.repository.name }}/build
      RAYLIB_PATH: ${{ github.event.repository.name }}/raylib

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: ${{ env.PROJECT_NAME }}

      # use latest version of raylib
      - name: Checkout raylib repo
        uses: actions/checkout@v3
        with:
          repository: raysan5/raylib
          path: raylib

      - name: Setup MinGW-w64
        uses: egor-tensin/setup-mingw@v2.2.0
        with:
          platform: x64

      - name: Build raylib
        run: |
          cd raylib/src
          make PLATFORM=PLATFORM_DESKTOP BUILD_MODE=RELEASE RAYLIB_LIBTYPE=STATIC

      - name: Build project
        run: |
          cd ${{ env.PROJECT_NAME }}
          mingw32-make PLATFORM=PLATFORM_DESKTOP
